---
name: Build containers
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - debian-bullseye
        - debian-buster
        - debian-stretch
        - ubuntu-bionic
        - ubuntu-focal
        - ubuntu-jammy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make 'docker-build-${{ matrix.os }}'
